import React from 'react';
import { ShieldAlert, CheckCircle2, AlertCircle } from 'lucide-react';
import { MOCK_TRANSACTIONS } from '../data/mockData';

export const ReportTemplate = React.forwardRef<HTMLDivElement, { currentScore: number }>((props, ref) => {
  const { currentScore } = props;

  return (
    <div 
      ref={ref} 
      className="bg-white text-slate-900 w-[794px] min-h-[1123px] absolute left-[-9999px] top-[-9999px] flex flex-col pt-12 pb-12"
      style={{ width: '794px' }} // A4 width at 96 DPI
    >
      {/* Page 1: Score & Explanation */}
      <div className="px-16 flex-1 flex flex-col h-[1123px] page-break-after">
        <div className="flex items-center gap-3 mb-8">
          <div className="w-8 h-8 bg-primary-600 rounded flex items-center justify-center shadow-sm">
            <div className="w-3 h-3 border-[2px] border-white rounded-sm"></div>
          </div>
          <span className="text-xl font-bold tracking-tight text-slate-800">CreditBud</span>
        </div>

        <h1 className="text-4xl font-black text-slate-800 mb-2 mt-8">Verifiable FinaScore Report</h1>
        <p className="text-slate-500 mb-12">Generated on {new Date().toLocaleDateString()}</p>

        <div className="bg-slate-50 border border-slate-200 rounded-2xl p-10 flex flex-col items-center text-center mb-12">
           <ShieldAlert className="w-16 h-16 text-primary-600 mb-6" />
           <p className="text-slate-500 font-bold tracking-widest uppercase text-sm mb-2">Verified FinaScore</p>
           <h2 className="text-8xl font-black text-slate-800 mb-2">{currentScore}</h2>
           <span className="text-lg font-bold text-emerald-600 uppercase tracking-widest">Great Standing</span>
        </div>

        <div className="space-y-6">
          <h3 className="text-xl font-bold text-slate-800 border-b border-slate-200 pb-2">Calculation Methodology</h3>
          <p className="text-slate-600 leading-relaxed text-sm">
            The FinaScore is a proprietary pseudo-credit score calculated using alternative data points, specifically tailored for cash-first and informal economies. This report is generated by securely analyzing the user's uploaded bank statements and parsed mobile money (MoMo) SMS notifications.
          </p>
          
          <div className="grid grid-cols-2 gap-6 mt-6">
            <div className="bg-white border border-slate-200 p-5 rounded-xl">
              <h4 className="font-bold text-slate-800 flex items-center gap-2 mb-2">
                <CheckCircle2 className="w-5 h-5 text-emerald-500" /> Payment Discipline
              </h4>
              <p className="text-xs text-slate-500">Weight: 40%. Analyzes consistency of utility and service payments via mobile money. No missed payments detected.</p>
            </div>
            <div className="bg-white border border-slate-200 p-5 rounded-xl">
               <h4 className="font-bold text-slate-800 flex items-center gap-2 mb-2">
                <CheckCircle2 className="w-5 h-5 text-emerald-500" /> Income Stability
              </h4>
              <p className="text-xs text-slate-500">Weight: 35%. Evaluates deposits across bank and mobile money. Shows regular primary income and variable secondary income.</p>
            </div>
            <div className="bg-white border border-slate-200 p-5 rounded-xl">
               <h4 className="font-bold text-slate-800 flex items-center gap-2 mb-2">
                <AlertCircle className="w-5 h-5 text-amber-500" /> Savings Rate
              </h4>
              <p className="text-xs text-slate-500">Weight: 15%. Measures % of income retained end-of-month. Currently lower than recommended average (5%).</p>
            </div>
             <div className="bg-white border border-slate-200 p-5 rounded-xl">
               <h4 className="font-bold text-slate-800 flex items-center gap-2 mb-2">
                <CheckCircle2 className="w-5 h-5 text-emerald-500" /> Financial Activity
              </h4>
              <p className="text-xs text-slate-500">Weight: 10%. Consistent daily usage of digital financial tools indicates strong integration into the formal digital economy.</p>
            </div>
          </div>
        </div>
      </div>

      <div style={{ pageBreakBefore: 'always' }} className="h-10 w-full" />

      {/* Page 2: Statement Backups */}
      <div className="px-16 flex-1 flex flex-col h-[1123px]">
         <h3 className="text-2xl font-bold text-slate-800 mb-8 mt-12">Verified Data Sources</h3>
         
         {/* Bank Statement Summary */}
         <div className="mb-10">
           <h4 className="text-sm font-bold tracking-widest uppercase text-slate-400 mb-4">Acme Bank - Account Ending in 4421</h4>
           <div className="border border-slate-200 rounded-xl overflow-hidden">
             <div className="bg-slate-50 px-6 py-3 border-b border-slate-200 grid grid-cols-4 gap-4 text-xs font-bold text-slate-500 uppercase tracking-widest">
               <div className="col-span-2">Description</div>
               <div>Date</div>
               <div className="text-right">Amount</div>
             </div>
             <div className="divide-y divide-slate-100">
               {MOCK_TRANSACTIONS.filter(t => t.source === 'bank').slice(0, 5).map(tx => (
                 <div key={tx.id} className="px-6 py-4 grid grid-cols-4 gap-4 text-sm">
                   <div className="col-span-2 font-bold text-slate-800">{tx.description}</div>
                   <div className="text-slate-500">{tx.date}</div>
                   <div className={`text-right font-bold ${tx.type === 'credit' ? 'text-emerald-600' : 'text-slate-800'}`}>
                     {tx.type === 'credit' ? '+' : '-'}${tx.amount}
                   </div>
                 </div>
               ))}
             </div>
           </div>
         </div>

         {/* Mobile Money Summary */}
         <div>
           <h4 className="text-sm font-bold tracking-widest uppercase text-slate-400 mb-4">Mobile Money - MT MoMo (Verified Number)</h4>
           <div className="border border-slate-200 rounded-xl overflow-hidden">
             <div className="bg-slate-50 px-6 py-3 border-b border-slate-200 grid grid-cols-4 gap-4 text-xs font-bold text-slate-500 uppercase tracking-widest">
               <div className="col-span-2">Parsed SMS Content</div>
               <div>Date</div>
               <div className="text-right">Amount</div>
             </div>
             <div className="divide-y divide-slate-100">
               {MOCK_TRANSACTIONS.filter(t => t.source === 'mobile_money').slice(0, 5).map(tx => (
                 <div key={tx.id} className="px-6 py-4 grid grid-cols-4 gap-4 text-sm">
                   <div className="col-span-2 font-bold text-slate-800">{tx.description} <span className="block text-[10px] text-slate-400 font-normal mt-1">Confirmed via SMS receipt</span></div>
                   <div className="text-slate-500">{tx.date}</div>
                   <div className={`text-right font-bold ${tx.type === 'credit' ? 'text-emerald-600' : 'text-slate-800'}`}>
                     {tx.type === 'credit' ? '+' : '-'}${tx.amount}
                   </div>
                 </div>
               ))}
             </div>
           </div>
         </div>

      </div>

    </div>
  );
});
